version: 1
update_configs:
- package_manager: "dotnet:nuget"
  directory: "/"
  update_schedule: "live"
  ignored_updates:
    - match:
        version_requirement: "*-beta"
  commit_message:
    prefix: "chore"
    include_scope: true
  default_labels:
  - dependencies
