name: Pull request check

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/build-lint-test.yml
    with:
      build_configuration: Debug
