name: Item Tracker CI

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'

env:
  Project_Name: MHWItemBoxTracker

defaults:
  run:
    shell: bash

jobs:
  interrupt:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    # https://github.com/actions/virtual-environments
    runs-on: windows-latest

    outputs:
      git_tag: ${{ steps.set_vars.outputs.git_tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - id: set_vars
      run: |
        # hacky workaround for the annotated tag push issue
        GIT_REF=${GITHUB_REF##*/}
        if [[ $GIT_REF == v* ]]
        then
          GIT_TAG=$GIT_REF
        else
          GIT_TAG=$(git describe --first-parent --abbrev=0)
        fi

        REV_COUNT=$(git rev-list $GIT_TAG..HEAD --count)
        echo "git_tag=$GIT_TAG.$REV_COUNT" >> $GITHUB_ENV
        echo "::set-output name=git_tag::$GIT_TAG.$REV_COUNT"

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the applications
      shell: pwsh
      run: |
        cp .github/NuGet.Config .
        msbuild $env:Project_Name.sln -m /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        NUGET_USERNAME: ${{ github.repository_owner }}
        NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the apps
      shell: pwsh
      run: |
        $version=$env:git_tag.substring(1)
        msbuild $env:Project_Name.sln -m /p:Configuration="$env:Configuration,VersionNumber=$version"
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Generate JSON
      if: matrix.configuration == 'Release'
      run: |
        nuget install Microsoft.Net.Compilers.Toolset -OutputDirectory packages -Version 3.9.0-2.final
        CSI="packages/Microsoft.Net.Compilers.Toolset.3.9.0-2.final/tasks/net472/csi.exe"

        # copy dlls for scripts to use
        cp ${Project_Name}/bin/Release/*.dll scripts/
        
        $CSI scripts/gen-json-schema.csx
        $CSI scripts/gen-module-json.csx
        $CSI scripts/gen-settings-json.csx
      env:
        NUGET_USERNAME: ${{ github.repository_owner }}
        NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  
    # Upload the builds for next job and debugging
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        # Don't know if this should be unique to the tag/branch/PR
        name: Item Tracker Plugin for Hunter Pie ${{ matrix.configuration }}
        path: ./**/bin/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: Item Tracker Plugin for Hunter Pie Release
    
    - name: Zip it
      run: |
        mkdir -p Modules/ItemBoxTracker
        RELEASE_DIR="${Project_Name}/bin/Release"
        mv ${RELEASE_DIR}/${Project_Name}.dll \
           ${RELEASE_DIR}/config.schema.json \
           ${RELEASE_DIR}/module.json \
           ${RELEASE_DIR}/settings.json \
           Modules/ItemBoxTracker
        zip ItemBoxTracker.zip -r Modules
  
    - name: Create release with binaries
      run: |
        BUILD=$(echo $GIT_TAG | cut -d'.' -f4)
        [[ $BUILD = 0 ]] && prerelease="" || prerelease="-p"
        gh release create $GIT_TAG -t "Release $GIT_TAG" $prerelease \
           ItemBoxTracker.zip \
           Modules/ItemBoxTracker/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_TAG: ${{ needs.build.outputs.git_tag }}
