name: Item Tracker CI

on:
  push:
    branches: [ master ]
    tags:
    - 'v*'

env:
  Project_Name: MHWItemBoxTracker

defaults:
  run:
    shell: bash

jobs:
  interrupt:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    # https://github.com/actions/virtual-environments
    runs-on: windows-latest

    outputs:
      git_tag: ${{ steps.set_vars.outputs.git_tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - id: set_vars
      run: |
        GIT_TAG=$(git describe --first-parent --tags)
        echo "::set-output name=git_tag::$GIT_TAG"

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the applications
      shell: pwsh
      run: msbuild $env:Project_Name.sln -m /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        NUGET_USERNAME: ${{ github.repository_owner }}
        NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the apps
      shell: pwsh
      run: msbuild $env:Project_Name.sln -m /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
  
    # Upload the builds for next job and debugging
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        # Don't know if this should be unique to the tag/branch/PR
        name: Item Tracker Plugin for Hunter Pie ${{ matrix.configuration }}
        path: ./**/bin/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: Item Tracker Plugin for Hunter Pie Release
  
    - name: Create release with binaries
      run: |
        gh release create $GIT_TAG -t "Release $GIT_TAG" \
          ${Project_Name}/bin/Release/${Project_Name}.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_TAG: ${{ needs.build.outputs.git_tag }}
