name: Item Tracker CI

on:
  pull_request:
    branches: [ master ]

env:
  Project_Name: ItemBoxTracker
  configuration: Debug

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the applications
      env:
        NUGET_USERNAME: ${{ github.repository_owner }}
        NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        cp .github/NuGet.Config .
        msbuild -m /t:Restore

    # - name: Execute unit tests
    #   run: dotnet test

    # if I had tests, I probably wouldn't need to build...
    - name: Build the apps
      shell: pwsh
      run: |
        msbuild -m /p:"Configuration=$env:configuration,AssemblyVersionNumber=0.0.0.0"
